# Generated by Django 4.2.4 on 2023-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=33)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.TextField(max_length=75)),
                ('twod', models.BooleanField(default=False)),
                ('treed', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
