# Generated by Django 4.2.4 on 2023-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=33)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.TextField(max_length=75)),
                ('twod', models.BooleanField(default=False)),
                ('treed', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField()),
                ('time_zone', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
