# Generated by Django 4.2.4 on 2023-09-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movies_salon_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seanslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='seans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.seanslar'),
        ),
    ]
