# Generated by Django 4.2.4 on 2023-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_seanslar_movies_seans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='seans',
        ),
        migrations.AddField(
            model_name='movies',
            name='seans_starttime',
            field=models.ManyToManyField(to='cinema.seanslar'),
        ),
    ]
