# Generated by Django 4.2.4 on 2023-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_remove_movies_seans_movies_seans_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='seans_starttime',
            field=models.ManyToManyField(related_name='seanslar', to='cinema.seanslar'),
        ),
        migrations.AlterField(
            model_name='seanslar',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seanslar',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
