# Generated by Django 4.2.4 on 2023-09-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_salon_no_remove_salon_time_zone_salon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='salon_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.salon'),
            preserve_default=False,
        ),
    ]
