# Generated by Django 4.2.4 on 2023-10-10 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_movies_salon_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trailer_url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='treed',
            new_name='threed',
        ),
        migrations.AddField(
            model_name='movies',
            name='image1',
            field=models.ImageField(default=123, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='image2',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='image3',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='imbd_rating',
            field=models.FloatField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='release_year',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
