# Generated by Django 4.2.4 on 2023-10-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_comingsoonmovie_rename_treed_movies_threed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Film türünün adı', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='turler',
            field=models.ManyToManyField(blank=True, help_text='Film türleri', to='cinema.genres'),
        ),
    ]
