# Generated by Django 4.2.4 on 2023-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_ticket_comingsoonmovie_cast_comingsoonmovie_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='salon_no',
        ),
    ]
