# Generated by Django 4.2.4 on 2023-11-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='showtime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='card_number',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='cvv',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='expiration_date',
            field=models.CharField(default=123, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='cinema.movies'),
            preserve_default=False,
        ),
    ]
